[general]

import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[font]

size = 10.5

normal = { family = "JetBrainsMono NF", style = "Semibold" }
bold = { family = "JetBrainsMono NF", style = "Bold" }
italic = { family = "JetBrainsMono NF", style = "Italic" }
bold_italic = { family = "JetBrainsMono NF", style = "Bold Italic" }

